import React from 'react';
import { usePageSeo } from '../hooks/usePageSeo';
import { Link } from 'react-router-dom';
import { ChevronLeft, FileText } from 'lucide-react';
import Logo from '../components/shared/Logo';
import { useUIStore } from '../store/useUIStore';

export default function TermsPage() {
  usePageSeo('Terms & Conditions', 'Read the BlinkBot Terms and Conditions — governing use of our AI chatbot platform, data rights, acceptable use policy, and billing.');
  const darkMode = useUIStore((state) => state.darkMode);

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
      <nav className="flex items-center justify-between px-8 py-6 max-w-4xl mx-auto border-b border-border/50">
        <div className="flex items-center gap-4">
          <Link to="/" className="p-2 rounded-lg hover:bg-muted text-muted-foreground hover:text-foreground transition-all">
            <ChevronLeft size={20} />
          </Link>
          <Logo />
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-8 py-12 pb-24">
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
              <FileText className="text-primary" size={20} />
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight">Terms and Conditions</h1>
          </div>
          <p className="text-muted-foreground text-lg">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="space-y-8 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using BlinkBot ("the Service"), you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">2. User Responsibilities & Account Security</h2>
            <p className="mb-2">
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>
            <p>
              You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">3. Acceptable Use Policy</h2>
            <p className="mb-2">
              When configuring AI agents or uploading documents to BlinkBot, you agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Upload malicious code, malware, or illicit material.</li>
              <li>Use the Service to generate hate speech, harassment, or illegal instructions.</li>
              <li>Attempt to reverse engineer, decompile, or bypass the security measures of the Service.</li>
              <li>Exceed the rate limits or storage capacities defined by your active subscription plan.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">4. Intellectual Property & Data Rights</h2>
            <p>
              You retain all rights to any documents, data, or text you upload to BlinkBot. We do not claim ownership of your data. However, you grant us a temporary, limited license to process, parse, and embed this data solely for the purpose of operating the Service (e.g., generating vector embeddings). We do not use your private data to train public foundation models.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">5. Limitation of Liability</h2>
            <p>
              In no event shall BlinkBot, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any AI hallucinations, inaccuracies, or erroneous outputs generated by the custom agents.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">6. Termination of Use</h2>
            <p>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease and all associated vector databases and documents may be permanently deleted.
            </p>
          </section>

          <section className="pt-8 border-t border-border/50">
            <h2 className="text-xl font-bold text-foreground mb-3">Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at support@blinkbot.in.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
