-- 0. Enable the pgvector extension first
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Create the 'agents' table
CREATE TABLE agents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  system_prompt TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the 'documents' table
CREATE TABLE documents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  agent_id UUID REFERENCES agents(id) ON DELETE CASCADE,
  filename TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create the 'document_embeddings' table

CREATE TABLE document_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  embedding VECTOR(384) 
);



-- 1. Ensure RLS is enabled on the agents table
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;

-- 2. Allow users to READ their own agents
CREATE POLICY "Users can view own agents" 
ON agents FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- 3. Allow users to CREATE their own agents
CREATE POLICY "Users can create own agents" 
ON agents FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- 4. Allow users to DELETE their own agents (future-proofing)
CREATE POLICY "Users can delete own agents" 
ON agents FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);


ALTER TABLE agents 
ADD COLUMN llm_provider TEXT DEFAULT 'groq',
ADD COLUMN llm_model TEXT DEFAULT 'llama-3.1-8b-instant',
ADD COLUMN api_key TEXT;

-- 1. CHAT SESSIONS TABLE (ChatGPT ke left sidebar ki lists ke liye)
CREATE TABLE chat_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    agent_id UUID REFERENCES agents(id) ON DELETE CASCADE,
    title TEXT DEFAULT 'New Conversation',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CHAT MESSAGES TABLE (Actual messages content hold karne ke liye)
CREATE TABLE chat_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id UUID REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL, -- 'user' ya 'assistant'
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Optimization Indexing for speed
CREATE INDEX idx_chat_sessions_agent ON chat_sessions(agent_id);
CREATE INDEX idx_chat_messages_session ON chat_messages(session_id);

ALTER TABLE chat_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages DISABLE ROW LEVEL SECURITY;


create table workspaces (
  id uuid primary key,
  name text not null,
  created_at timestamptz default now()
);

create table workspace_members (
  id uuid primary key,
  workspace_id uuid,
  user_id uuid,
  role text
);